### ISSUE TITLE
U5 hw5 question3

### ISSUE THREAD

**Issue by lvyhnzhng** [Enchanted-Millet/homework-nodejs#10]
var longestCommonPrefix = function(strs) {
    if (!strs.length) return '';
    let prefix = '';
    let maxPrefixLength = Math.min(...strs.map(str => str.length)); ///...?
    for (let i = 0; i < maxPrefixLength; i++) {
      let char = strs[0][i]; //？
      if (strs.every(str => str[i] === char)) { 
        prefix += char;
      } else {
        break;
      }
    };  
    return prefix;
  };

**Comment by Enchanted-Millet** [comment]
`let maxPrefixLength = Math.min(...strs.map(str => str.length));` 这句话是用来找到 common prefix 的最大的长度，map function 把所有 string 的长度拿到，放到一个新的 array 里，然后再用 Math.min 得到其中最短的，也就是 common prefix 最大长度的可能
