### ISSUE TITLE
U5 hw4

### ISSUE THREAD

**Issue by lvyhnzhng** [Enchanted-Millet/homework-nodejs#11]
const regex =
        /^(?=(.*[A-Z]){1,})(?=(.*[0-9]){1,})(?=(.*[a-z]){1,})(?!.*\W).{6,10}$/;

questions:

^
?= and ?!   
.*

**Comment by Enchanted-Millet** [comment]
@lvyhnzhng https://www.cnblogs.com/deerchao/archive/2006/08/24/zhengzhe30fengzhongjiaocheng.html
这是一篇很好的讲解正则表达式的文章，清晰明了，希望对你有帮助
