### ISSUE TITLE
U5--hw3 questions

### ISSUE THREAD

**Issue by lvyhnzhng** [Enchanted-Millet/homework-nodejs#9]
example 1: 
why the output is:
(75) ['9', '9', 'b', 'o', 't', 't', 'l', 'e', 's', 'o', 'f', 'b', 'e', 'e', 'r', 'o', 'n', 't', 'h', 'e', 'w', 'a', 'l', 'l', 't', 'a', 'k', 'e', '1', 'd', 'o', 'w', 'n', 'a', 'n', 'd', 'p', 'a', 's', 's', 'i', 't', 'a', 'r', 'o', 'u', 'n', 'd', '-', '-', '9', '8', 'b', 'o', 't', 't', 'l', 'e', 's', 'o', 'f', 'b', 'e', 'e', 'r', 'o', 'n', 't', 'h', 'e', 'w', 'a', 'l', 'l', '.']
why at here we can use .match( ) on a string?

**Comment by Enchanted-Millet** [comment]
@lvyhnzhng for your reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match#return_value
